Disable win32 build

diff --git a/Scripts/post-commit b/Scripts/post-commit
--- a/Scripts/post-commit
+++ b/Scripts/post-commit
@@ -133,13 +133,13 @@ function windows_msbuild {
 
 		cd $CTRLR_ROOT/Builds/VisualStudio2019
 		
-		echo "CTRLR: Build Win32"
-		"$MSBUILD" Ctrlr.sln /target:Rebuild /fileloggerparameters:logfile=Ctrlr-$VERSION.win32.build.log /property:Configuration=Release_Win32 /property:VisualStudioVersion=15.0 
+		# echo "CTRLR: Build Win32"
+		# "$MSBUILD" Ctrlr.sln /target:Rebuild /fileloggerparameters:logfile=Ctrlr-$VERSION.win32.build.log /property:Configuration=Release_Win32 /property:VisualStudioVersion=15.0 
 		
-		if [ $? -ne 0 ]; then
-			echo "CTRLR: Win32 build failed"
-			exit 1
-		fi
+		# if [ $? -ne 0 ]; then
+		# 	echo "CTRLR: Win32 build failed"
+		# 	exit 1
+		# fi
 		echo "CTRLR: Build x64"
 		
 		"$MSBUILD" Ctrlr.sln /target:Rebuild /fileloggerparameters:logfile=Ctrlr-$VERSION.win64.build.log /property:Configuration=Release /property:VisualStudioVersion=15.0 /property:Platform=x64
